---
# Source: base/templates/application-cert-manager.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: namespaced
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaced
  namespace: namespaced
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: namespaced
    server: https://kubernetes.default.svc
  project: base
  source:
    path: namespaced
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD