apiVersion: v1
data:
  auth: {{ htpasswd .Values.kafka_ui.credentials.username .Values.kafka_ui.credentials.password | b64enc | quote }}
kind: Secret
metadata:
  name: kafka-ui-basic-auth
  namespace: {{.Values.kafka_ui.namespace}}
type: Opaque
---
{{- template "application" $.Values.kafka_ui }}
      values: |
        yamlApplicationConfig:
          kafka:
            clusters:{{ include "kafka.ui.clusters" $.Values.solutions.kafka.configs | indent 14}}
        # Ingress configuration
        ingress:
          # Enable ingress resource
          enabled: true

          # Annotations for the Ingress
          annotations: 

            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/auth-type: basic
            nginx.ingress.kubernetes.io/auth-secret: kafka-ui-basic-auth
            nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'

          # ingressClassName for the Ingress
          ingressClassName: "nginx"

          # The path for the Ingress
          path: "/"

          # The path type for the Ingress
          pathType: "Prefix"  

          # The hostname for the Ingress
          host: "{{.Values.kafka_ui.subdomain}}.{{.Values.domain}}"

          # configs for Ingress TLS
          tls:
            # Enable TLS termination for the Ingress
            enabled: true
            # the name of a pre-created Secret containing a TLS private key and certificate
            secretName: "kafka-ui-tls"

          # HTTP paths to add to the Ingress before the default path
          precedingPaths: []

          # Http paths to add to the Ingress after the default path
          succeedingPaths: []