---
# Source: base/templates/application-cert-manager.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: namespaced
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaced
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://nieo.tplinkdns.com:6443
  project: child
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD