{{- template "application" $.Values.vector }}
      values: |
        customConfig: 
          data_dir: /vector-data-dir
          api:
            enabled: true
            address: 127.0.0.1:8686
            playground: false
          sources: {{ include "vector.sources" $.Values.vector.sources | indent 12}}
          sinks: {{ include "vector.services" $.Values.vector.services | indent 12}}
