apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
  name: {{.Values.name}}
spec:
  acme:
    email: {{.Values.email}}
    preferredChain: ''
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx