apiVersion: apps/v1
kind: Deployment
metadata:
  name: flog
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flog-app
  template:
    metadata:
      annotations:
        prometheus.io/probe: "true"
      labels:
        monitor: vector
        app: flog-app
    spec:
      containers:
      - name: flog
        image: mingrammer/flog
        args: ['-l','-d','.01']

      


