apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-server
  template:
    metadata:
      labels:
        app: httpd-server
        monitor: vector
      annotations:
        prometheus.io/probe: "true"
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
      # nodeSelector:
      #   node: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: http
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/probe-path: "/"
spec:
  selector:
    app: httpd-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP
  sessionAffinity: None