apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: kafka
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  kafka:
    brokers: {{.Values.fluentbit.output.kafka.cluster}}-kafka-bootstrap.kafka.svc.cluster.local:9092
    topics: {{.Values.fluentbit.output.kafka.topic}}
---